services:
  nginx:
    image: ${SERVICE_IMAGE_NAME}${SERVICE_IMAGE_TAG:+:${SERVICE_IMAGE_TAG}}${SERVICE_IMAGE_DIGEST:+@${SERVICE_IMAGE_DIGEST}}
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
      - FOO=${FOO}