name: "🪧 Task to complete"
description: "If something needs to be done"
title: "🪧 [TASK] - "
labels: [
  "enhancement"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your task
      placeholder: Short and explicit description of your task...
    validations:
      required: true