name: "💡 Feature Request"
description: Create ticket for a new feature request
title: "💡 [REQUEST] - "
labels: [
  "question"
]
body:
  - type: input
    id: start_date
    attributes:
      label: "Start Date"
      description: Start of development
      placeholder: "DD.MM.YYYY"
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: basic_usage
    attributes:
      label: "Basic Usage"
      description: Indicate here some basic examples of your feature.
      placeholder: |
        A few specific words about your feature request.
        how do you see this feature to work and use for.
    validations:
      required: true
  - type: textarea
    id: unresolved_question
    attributes:
      label: "Unresolved questions"
      description: What questions still remain unresolved ?
      placeholder: Identify any unresolved issues or Discussion links to admit
    validations:
      required: false