# File .github/workflows/template-sync.yml
# DESCRIPTION: automate synchronization with TEMPLATE repo.
#              template changes will be applied to project repo (except: .templatesyncignore)

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

env:
  SOURCE_BRANCH:     master
  SOURCE_REPOSITORY: wlgdev/template-repository

  SYNC_APP_ID:        ${{ secrets.WLGDEV_SYNCAPP_APP_ID }}
  SYNC_CLIENT_ID:     ${{ secrets.WLGDEV_SYNCAPP_CLIENT_ID }}
  SYNC_CLIENT_SECRET: ${{ secrets.WLGDEV_SYNCAPP_CLIENT_SECRET }}
  SYNC_PRIVATE_KEY:   ${{ secrets.WLGDEV_SYNCAPP_PRIVATE_KEY }}

jobs:
  template-sync:
    if: ${{ !startsWith(github.repository, 'wlgdev/template-') }}
    runs-on: ubuntu-latest
    permissions: # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      contents: write
      pull-requests: write

    steps:
      - name: Auth # https://github.com/tibdex/github-app-token
        id: auth
        uses: tibdex/github-app-token@v2
        with:
          app_id:      ${{ env.SYNC_APP_ID }}
          private_key: ${{ env.SYNC_PRIVATE_KEY }}

      - name: Checkout # https://github.com/actions/checkout#usage
        uses: actions/checkout@v4
        with:
          token: '${{ steps.auth.outputs.token }}'

      - name: actions-template-sync # https://github.com/marketplace/actions/actions-template-sync#usage
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_gh_token: ${{ steps.auth.outputs.token }}
          source_repo_path: ${{ env.SOURCE_REPOSITORY }}
          upstream_branch: ${{ env.SOURCE_BRANCH }}
          template_sync_ignore_file_path: "./.github/.templatesyncignore"
          pr_branch_name_prefix: "sync/upstream_change"
          pr_commit_msg: "sync(template): merge template changes :up:"
          pr_labels: "template_sync,upstream,sync"
          pr_title: "[UPSTREAM] Template Repository - synchronize"
